#!/usr/bin/env bash
# Restarts nginx server to listen on port 80
sed -i 's/\slisten 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/\slisten [::]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
service nginx restart
