#!/usr/bin/env bash
# Displays numbers from 1 to 100. Displays FizzBuzz instead of a multiple of 3
# and 5. Displays Fizz instead of a multiple of 3. Displays Buzz instead of a
# multiple of 5.

for i in {1..100}; do

	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
		echo "FizzBuzz"

	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"

	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"

	else
		echo "$i"
	fi
done
