#!/usr/bin/env bash
# Displays numbers from 1 to 20 with extra information on bad luck numbers
# from China(4), Japan(9) and Italy(17)

i=1
while [ $i -le 20 ]; do
	echo "$i"

	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac

	(( i += 1 ))
done
