#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

h=0
m=1
while [ $h -le 12 ]; do
	echo "Hour: $h"

	while [ $m -lt 60 ]; do
		echo "$m"
		(( m += 1 ))
	done

	m=1
	(( h += 1 ))
done
