#!/usr/bin/env bash
# Configures an Ubuntu server so that:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i -E 's/^.+?\s+localhost$/127.0.0.2\tlocalhost/' ~/hosts.new
printf "8.8.8.8\tfacebook.com\n" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
