#!/usr/bin/env bash
# Runs Nginx as the user nginx
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/#user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/( |:)80 /\18080 /' /etc/nginx/sites-enabled/default
pkill apache
sudo -u nginx service nginx restart
